### ISSUE TITLE
dead link

### ISSUE THREAD

**Issue by rfarouni** [mgtools/myRT#1]
Hi,

This link in the instructions is dead. Is there an updated link available?

wget https://omics.sice.indiana.edu/myRT/Models/cdd-pfamA.tar.gz -P Models/

Thank you
Rick

**Comment by fsharifi** [comment]
Please use one of the links below: 

https://omics.sice.indiana.edu/myRT/share/cdd-pfamA.tar.gz 
https://omics.sice.indiana.edu/myRT/Models/cdd-pfamA.tar.gz
